# Lab 6 (Week 2 — Lab 1): Introduction to Machine Learning

**Name:** Numair Fahad

**Role:** AI/ML Intern

**Company:** Zynvex Solutions

**GitHub:** https://github.com/numair-2003/AIML-Internship-NumairFahad

Welcome to Week 2! In this lab you will practice the foundational steps of every machine learning project: loading data, splitting it into training and test sets, and preparing it for models to learn from.

**For detailed theory on ML concepts, overfitting, underfitting, and why train-test splits matter, see the Lab 6 PDF and Learning Resources.**

This notebook focuses on the practical, hands-on workflow.

## Example 1: Loading & Exploring Data

We'll use the Iris dataset — a classic dataset with measurements of 150 iris flowers across three species.

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

# Load the Iris dataset
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

Dataset shape: (150, 5)

First 5 rows:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [2]:
print("Column names:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nTarget classes:")
print(df['species'].value_counts())

Column names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

Data types:
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species               object
dtype: object

Target classes:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


## Example 2: Train-Test Split

The most important step: split your data so you can train on one part and test on another (unseen) part.

In [3]:
from sklearn.model_selection import train_test_split

X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])
print("\nTraining set - first 3 rows:")
print(X_train.head(3))

Training set size: 120
Test set size: 30

Training set - first 3 rows:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4


## Example 3: Feature Scaling

When features are on different scales, models learn better if you standardize them.

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Original training data (first 3 rows):")
print(X_train.head(3))
print("\nScaled training data (first 3 rows):")
print(X_train_scaled[:3])
print("\nScaled data - mean (should be ~0):", X_train_scaled.mean())
print("Scaled data - std dev (should be ~1):", X_train_scaled.std())

Original training data (first 3 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4

Scaled training data (first 3 rows):
[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]]

Scaled data - mean (should be ~0): -5.181040781584064e-17
Scaled data - std dev (should be ~1): 0.9999999999999999


## Practice Exercise 1: Train-Test Split with Different Test Size

**Exercise:** Split the Iris data with test_size=0.3 (30% for testing) instead of 0.2. Print the new sizes.

In [5]:
### YOUR CODE HERE ###
X_train_alt, X_test_alt, y_train_alt, y_test_alt = train_test_split(X, y, test_size=0.3, random_state=42)
### END ###

print("New training set size:", X_train_alt.shape[0])
print("New test set size:", X_test_alt.shape[0])

New training set size: 105
New test set size: 45


**Expected Output:**
```
New training set size: 105
New test set size: 45
```

## Practice Exercise 2: Check Scaled Data Statistics

**Exercise:** After scaling the training set (as shown in Example 3), verify that the mean of each feature is close to 0 and the standard deviation is close to 1. Print both for the scaled training data.

In [6]:
### YOUR CODE HERE ###
print("Mean of each feature: ", X_train_scaled.mean(axis=0))
print("Standard deviation of each feature: ", X_train_scaled.std(axis=0))

print("\nOriginal sepal length - min to max:")
print(f"Min: {X_train['sepal length (cm)'].min()}, Max: {X_train['sepal length (cm)'].max()}")

print("\nScaled sepal length - min to max:")
print(f"Min: {X_train_scaled[:, 0].min():.2f}, Max: {X_train_scaled[:, 0].max():.2f}")
### END ###

Mean of each feature:  [ 1.71344420e-15 -1.66579713e-15 -2.23894977e-16 -5.73615229e-17]
Standard deviation of each feature:  [1. 1. 1. 1.]

Original sepal length - min to max:
Min: 4.3, Max: 7.7

Scaled sepal length - min to max:
Min: -1.84, Max: 2.30


## Practice Exercise 3: Scaling the Test Set

**Exercise:** Use the fitted scaler (from Example 3) to scale the test set X_test. Important: always use `.transform()` on test data, NOT `.fit_transform()`. Print the first 3 rows of scaled test data.

In [7]:
### YOUR CODE HERE ###
X_test_scaled = scaler.transform(X_test)
print(f"Scaled test data (first 3 rows):\n", X_test_scaled[:3])
### END ###

Scaled test data (first 3 rows):
 [[ 0.35451684 -0.58505976  0.55777524  0.02224751]
 [-0.13307079  1.65083742 -1.16139502 -1.17911778]
 [ 2.30486738 -1.0322392   1.8185001   1.49058286]]


## Lab Tasks

Complete the following in this notebook, below this cell.

1. **Data Inspection**: Load the Iris dataset (as shown in Example 1) and describe what you find: number of rows, columns, any missing values, and the distribution of the three species classes.
2. **Train-Test Split**: Split the Iris data into 75% training and 25% testing (different from the 80-20 split shown in examples). Print both set sizes.
3. **Feature Scaling**: Scale both the training and test sets using StandardScaler. Verify that the mean and standard deviation of the scaled training data are correct.
4. **Understanding the Workflow**: In a markdown cell, explain in 3-4 sentences why we split data into training and test sets, and why scaling features helps models learn better. Use simple language.
5. **Reflection**: Write 2-3 sentences on what you learned in this lab and what questions remain before you start building actual models next lab.

In [13]:
# Task 1
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

print("Number of rows: ", df.shape[0])
print("\nNumber of columns: ", df.shape[1])
print("\nMissing values: ", df.isnull().sum())
print("\nDistribution of three species: ", df['species'].value_counts())




Number of rows:  150

Number of columns:  5

Missing values:  sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

Distribution of three species:  species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


In [16]:
# Task 2
from sklearn.model_selection import train_test_split

X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print("Training set size: ", X_train.shape[0])
print("Test set size: ", X_test.shape[0])

Training set size:  112
Test set size:  38


In [18]:
# Task 3
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Original training data: ", X_train.head(5))
print("\nScaled training data: ")
print(X_train_scaled[:5])

print("\nMean of each feature - scaled training data: ", X_train_scaled.mean(axis=0))
print("\nStandard deviation of each feature - scaled training data: ", X_train_scaled.std(axis=0))


Original training data:       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
4                  5.0               3.6                1.4               0.2
32                 5.2               4.1                1.5               0.1
142                5.8               2.7                5.1               1.9
85                 6.0               3.4                4.5               1.6
86                 6.7               3.1                4.7               1.5

Scaled training data: 
[[-1.01827123  1.2864604  -1.39338902 -1.3621769 ]
 [-0.7730102   2.43545215 -1.33550342 -1.49647603]
 [-0.03722712 -0.78172474  0.74837808  0.92090833]
 [ 0.20803391  0.8268637   0.4010645   0.51801093]
 [ 1.06644751  0.13746866  0.51683569  0.3837118 ]]

Mean of each feature - scaled training data:  [ 1.72282823e-15 -4.64410256e-16 -4.24263799e-16  7.07767178e-16]

Standard deviation of each feature - scaled training data:  [1. 1. 1. 1.]


# Task 4 (markdown explanation)

We split the data into **training** and **test sets** to train the model on one, known part of the data and evaluate and test its performance on the new, unseen data. This helps us understand how well the model will generalize to new examples.

**Feature scaling** is significant because features (columns) can be on very different scales. It brings all features to a similar range (mean ≈ 0 and standard deviation ≈ 1), which enables models to learn more effectively from patterns and prevents features with larger values from dominating the learning process.

# Task 5 (Reflection)

In this lab, I learned how to load a dataset, inspect it, split it into training and test sets, and apply feature scaling using StandardScaler. I also understood the importance of using .fit_transform() only on the training data and .transform() on the test data to avoid data leakage and prevent the scaler from viewing the information from the test set.

One question that remains is how different scaling methods (e.g. MinMaxScaler) compare to StandardScaler when building actual machine learning models in the next lab.

In [19]:
from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/numair-2003/AIML-Internship-NumairFahad.git

Mounted at /content/drive
Cloning into 'AIML-Internship-NumairFahad'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 48 (delta 19), reused 17 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (48/48), 839.97 KiB | 19.53 MiB/s, done.
Resolving deltas: 100% (19/19), done.


In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/Lab 06_NumairFahad.ipynb" "/content/AIML-Internship-NumairFahad/"